name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Проверка версии Docker и Docker Compose
        run: |
          docker --version
          docker-compose --version

      - name: Сборка образов
        run: docker-compose build

      - name: Запуск контейнеров
        run: docker-compose up -d

      - name: Проверка работы контейнера
        run: |
          docker ps
          curl http://localhost:5000  # Для проверки работы backend

      - name: Push images to Docker Hub
        run: |
          docker-compose push

      - name: Остановка контейнеров
        run: docker-compose down
